### ISSUE TITLE
Can't get message author nickname

### ISSUE THREAD

**Issue by Nimon77** [Breq16/flask-discord-interactions#115]
**Describe the bug**
Can't get message author nickname

**Categorization**
This issue impacts...
- [x] The library itself
- [ ] Documentation
- [ ] Examples

**To Reproduce**
1. Create an `ApplicationCommandType.MESSAGE`
2. Try to get the nickname of the message author
3. We get `message.author.nick=None`

**Expected behavior**
`message.author.nick` not None

**Environment**
I am using... (check any that apply, leave unchecked if you don't know)
- [ ] Quart and/or Asyncio
- [ ] A "Bot User"
- [ ] Additional Flask extensions (SQLAlchemy, Flask-CORS, etc.)
- [ ] Additional backend services (Redis, RQ, Celery)

**Additional context**

**Comment by Breq16** [comment]
Unfortunately this isn't something that this library can support, since the Discord API doesn't return all member data for a message. Specifically, the `author` field of the [message object](https://discord.com/developers/docs/resources/channel#message-object) only provides a user object, not a member object.

If you want this functionality, the best way to make your voice heard is the discord docs repo. The most similar issue to this right now is discord/discord-api-docs#3258.
