### ISSUE TITLE
init_app doesnt set app

### ISSUE THREAD

**Issue by ahmedbodi** [Breq16/flask-discord-interactions#15]
Hey mate

Found a bug while using the library, When calling init_app, the library doesnt set self.app to the app variable thats passed in causing an error when registering the route

**Comment by Breq16** [comment]
This is intended behavior, so that people can use the Flask [Application Factory](https://flask.palletsprojects.com/en/1.1.x/patterns/appfactories/) pattern without binding the application to the extension.

You shouldn't have to call `init_app` manually if you don't want to use this pattern. The [constructor](https://github.com/Breq16/flask-discord-interactions/blob/45aad52307ef9a0335c53b87d9f1b32273b11577/flask_discord_interactions/discord.py#L105) of the `DiscordInteractions` object sets the `self.app` variable, and handles calling `init_app` for you.

I would suggest looking at the [tutorial](https://flask-discord-interactions.readthedocs.io/en/latest/botsetup.html#run-the-program) if you want an example of how to use this library.

**Comment by ahmedbodi** [comment]
How can the library create the routes without binding to the application then?

**Comment by ahmedbodi** [comment]
I'm using the app factory pattern myself in my application, however im forced to do the following

```
def extensions(app):
    """
    Register 0 or more extensions (mutates the app passed in).
    :param app: Flask application instance
    :return: None
    """
    debug_toolbar.init_app(app)
    flask_static_digest.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    seeder.init_app(app, db)

    discord.app = app
    discord.init_app(app)
    discord.register_blueprint(commands.bp)
    discord.set_route("/interactions")
    discord.update_slash_commands(guild_id=DEFAULT_GUILD)

    return None
```

**Comment by Breq16** [comment]
> How can the library create the routes without binding to the application then?

Pass the application in as a parameter, as per the [documentation](https://flask-discord-interactions.readthedocs.io/en/latest/discord.html#flask_discord_interactions.DiscordInteractions.set_route).

```python
discord.init_app(app)
discord.register_blueprint(commands.bp)
discord.set_route("/interactions", app=app)
discord.update_slash_commands(guild_id=...)
```
