### ISSUE TITLE
discord.command_group() does not work.

### ISSUE THREAD

**Issue by TheDevFreak** [Breq16/flask-discord-interactions#43]
According to the documentation syntax like the following can be used:
```py
comic = discord.command_group("comic")


@comic.command()
def xkcd(ctx, number: int):
    return f"https://xkcd.com/{number}/"
```

However doing this results in the following in the logs:
`AttributeError: 'SlashCommandGroup' object has no attribute 'default_permission'`
if `discord.update_slash_commands()` is being used

**Comment by Breq16** [comment]
Looks like this bug was introduced [here](https://github.com/Breq16/flask-discord-interactions/pull/40/commits/95dce1e6e2c3dfda2b63f840b322562def4a70c2#diff-aa1c16ef0ec9ef5e0d60d5641b9f61a84fac5bbd233b7f7d8ea3ffa3bda88a64R195), as the permissions registration code assumes that all Commands will have a permissions array.

I've pushed a new release, v1.0.1, that should resolve this issue. `pip3 install Flask-Discord-Interactions=1.0.1` should download this new version.

**Comment by TheDevFreak** [comment]
Can confirm the issue is fixed. 👍
