### ISSUE TITLE
Application Command Types

### ISSUE THREAD

**Issue by fmdaboville** [Breq16/flask-discord-interactions#50]
This is a simple question to know if you plan to handle ohers [Application Command Types](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-types) ?

For example, like [user commands](https://discord.com/developers/docs/interactions/application-commands#user-commands) and [message commands](https://discord.com/developers/docs/interactions/application-commands#message-commands) ?

Thanks

**Comment by Breq16** [comment]
I probably don't have the time to implement those right away, but I would like them to be implemented eventually. If you (or anyone else) wants to submit a pull request adding this functionality, though, I'd be happy to review and merge 👍

**Comment by fmdaboville** [comment]
I start to make some changes, I will submit a pull request once evrything is ready.
Do you have any contributing guide with specificities for your repo ?
How should I deal with documentation ?

**Comment by Breq16** [comment]
I don't have any specific contributor guide at the moment. I'd say, generally, try to follow [PEP8](https://pep8.org/), but as long as everything's readable enough, it's fine.

The documentation lives in the `/docs` directory. The project uses Sphinx, so the docs are written in reStructuredText. If you're familiar with the syntax (or willing to learn), feel free to give this a try. Otherwise, I'm fine with writing the docs myself.
