### ISSUE TITLE
usage in blueprint

### ISSUE THREAD

**Issue by gata1526** [Breq16/flask-discord-interactions#8]
Can you use those into blueprint? It's working in a single file, but not viable for large app.

**Comment by Breq16** [comment]
You can't use multiple Flask blueprints with this library, since Discord sends all the commands to the same URL. However, this library does provide a `DiscordInteractionsBlueprint` class that functions similarly and should allow you to split your code into multiple files. You can see an example of this [here](https://github.com/Breq16/flask-discord-interactions/blob/main/examples/basic.py#L190).
