### ISSUE TITLE
Question: Why?

### ISSUE THREAD

**Issue by RGBCube** [Breq16/flask-discord-interactions#80]
discord.py already has tree's (slash)

**Comment by TheJaffaMeme** [comment]
I myself run a bot with this library and I believe it's still one of the best python libraries to run a slash command bot. It allows for a bot to be ran on so called "serverless architecture". Rather than the bot constantly listening in like it would for discord.py, this library makes use of an interactions endpoint instead. This is where discord will reach out to your bot endpoint URL when it is required. By doing so you eliminate the need for a 24/7 listener and only take requests for actual slash commands (rather than receiving all messages in all guilds). This allows for deployment on scale to 0 services such as google cloud run, heroku etc. as well as what I can imagine to be substantially reduced bot load.

**Comment by RGBCube** [comment]
i see
